(() => {
  const source = "Google Books Ngram v3, English 2010-2019";
  const phrase = (
    id,
    text,
    meaning,
    note,
    example,
    exampleJa,
    gram,
    rank,
    freq,
    tags = [],
    corpusText = text
  ) => ({
    id,
    text,
    corpusText,
    meaning,
    note,
    example,
    exampleJa,
    gram,
    rank,
    freq,
    source,
    tags
  });

  window.PHRASES = [
    phrase("p001", "as well as", "...だけでなく...も / ...と同じくらい", "追加の意味で使うことが多く、文脈によって比較にもなる。", "She speaks Spanish as well as English.", "彼女は英語だけでなくスペイン語も話します。", 3, 3, 52977493, ["addition", "comparison"]),
    phrase("p002", "in order to", "...するために", "目的をはっきり言う表現。toだけより少し硬め。", "I left early in order to catch the train.", "電車に乗るために早く出ました。", 3, 4, 37668834, ["purpose"]),
    phrase("p003", "one of the", "...のうちの1つ / 1人", "最上級や複数名詞とよく一緒に使う。", "This is one of the best places to start.", "ここは始めるのに最適な場所の一つです。", 3, 1, 66464125, ["quantity"]),
    phrase("p004", "out of the", "...の外へ / ...の中から", "移動、材料、選択など複数の意味を持つので後ろの名詞で判断する。", "She walked out of the room.", "彼女は部屋から出ていきました。", 3, 6, 35937786, ["movement"]),
    phrase("p005", "part of the", "...の一部", "物理的な一部にも、抽象的な構成要素にも使える。", "Listening is part of the process.", "聞くことはその過程の一部です。", 3, 7, 33575003, ["structure"]),
    phrase("p006", "do not know", "わからない / 知らない", "知識がない時も、判断できない時も使える。", "I do not know the answer yet.", "まだ答えはわかりません。", 3, 11, 25865707, ["thinking"]),
    phrase("p007", "the fact that", "...という事実", "that以下を名詞のかたまりとして扱う。", "The fact that he waited mattered to her.", "彼が待ったという事実が彼女には大事でした。", 3, 12, 25529166, ["logic"]),
    phrase("p008", "some of the", "...のいくつか / 一部", "全部ではなく一部を取り出す時に使う。", "Some of the ideas were useful.", "そのアイデアのいくつかは役に立ちました。", 3, 13, 25402042, ["quantity"]),
    phrase("p009", "there is a", "...がある / いる", "新しいものを会話に出す時の基本形。", "There is a small cafe near the station.", "駅の近くに小さなカフェがあります。", 3, 14, 24779276, ["existence"]),
    phrase("p010", "be able to", "...できる", "canよりも時制や助動詞と組み合わせやすい。", "You will be able to use it offline.", "それはオフラインでも使えるようになります。", 3, 19, 23108040, ["ability"]),
    phrase("p011", "there is no", "...がない / いない", "存在しないことをはっきり言う形。", "There is no simple answer.", "簡単な答えはありません。", 3, 22, 22929461, ["existence", "negative"]),
    phrase("p012", "a number of", "いくつかの / かなりの数の", "後ろは複数名詞。数がある程度あることを示す。", "A number of people joined the test.", "何人もの人がテストに参加しました。", 3, 27, 21769223, ["quantity"]),
    phrase("p013", "in terms of", "...の観点では", "評価軸や話題の範囲を限定する。", "In terms of speed, this version is better.", "速度の面では、この版の方が良いです。", 3, 29, 20849457, ["scope"]),
    phrase("p014", "in front of", "...の前に", "場所の前だけでなく、人前という意味にも広がる。", "He spoke in front of the class.", "彼はクラスの前で話しました。", 3, 31, 20772901, ["place"]),
    phrase("p015", "a lot of", "たくさんの", "数えられる名詞にも数えられない名詞にも使いやすい。", "A lot of learners need phrases, not just words.", "多くの学習者には単語だけでなくフレーズが必要です。", 3, 37, 18338349, ["quantity"]),
    phrase("p016", "most of the", "...の大部分", "集団や範囲の中の大半を指す。", "Most of the cards are short.", "カードの大半は短いです。", 3, 45, 15957790, ["quantity"]),
    phrase("p017", "as a result", "その結果", "前の内容から自然に起きた結果をつなぐ。", "She practiced daily. As a result, she improved quickly.", "彼女は毎日練習しました。その結果、すぐに上達しました。", 3, 47, 15880529, ["result"]),
    phrase("p018", "according to the", "...によると", "情報源を示す。theの後ろにreport, data, studyなどが来やすい。", "According to the data, the phrase is common.", "データによると、そのフレーズはよく使われます。", 3, 49, 15348021, ["source"]),
    phrase("p019", "based on the", "...に基づいて", "根拠や材料を示す。", "The deck is based on the frequency list.", "このデッキは頻度リストに基づいています。", 3, 51, 15145562, ["source"]),
    phrase("p020", "because of the", "...のために / ...が原因で", "名詞句を原因として置く。because節とは形が違う。", "Because of the rain, we stayed inside.", "雨のため、私たちは中にいました。", 3, 78, 12903508, ["cause"]),
    phrase("p021", "as soon as", "...するとすぐに", "時間の接続表現。未来のことでも後ろは現在形が多い。", "I will call you as soon as I arrive.", "着いたらすぐに電話します。", 3, 85, 12492028, ["time"]),
    phrase("p022", "in addition to", "...に加えて", "追加する対象を名詞句で置く。", "In addition to phrases, examples help.", "フレーズに加えて、例文も役に立ちます。", 3, 90, 12155669, ["addition"]),
    phrase("p023", "due to the", "...が原因で / ...のため", "原因を少し硬めに示す。", "The delay was due to the weather.", "遅れは天候が原因でした。", 3, 91, 12082938, ["cause"]),
    phrase("p024", "a couple of", "2つの / いくつかの", "厳密に2つの時も、少数の時もある。", "I need a couple of minutes.", "数分ください。", 3, 93, 11601331, ["quantity"]),
    phrase("p025", "at the same time", "同時に / とはいえ", "時間が同じという意味に加え、対比を足す時にも使う。", "The app is simple. At the same time, it saves progress.", "アプリはシンプルです。同時に、進捗も保存します。", 4, 2, 17297644, ["time", "contrast"]),
    phrase("p026", "I do not know", "わかりません", "丁寧に書く形。会話ではI don't knowも多い。", "I do not know where to start.", "どこから始めればいいかわかりません。", 4, 1, 17575369, ["thinking"]),
    phrase("p027", "on the other hand", "一方で", "対比をはっきり作る定番表現。", "The word is easy. On the other hand, the phrase is useful.", "単語は簡単です。一方で、そのフレーズは役に立ちます。", 4, 6, 13356239, ["contrast"]),
    phrase("p028", "in the case of", "...の場合は", "特定の例や条件に話を絞る。", "In the case of beginners, short phrases work well.", "初心者の場合、短いフレーズがよく効きます。", 4, 7, 11636010, ["condition"]),
    phrase("p029", "as a result of", "...の結果として", "原因となった名詞句を続ける。", "As a result of practice, she became faster.", "練習の結果、彼女は速くなりました。", 4, 13, 8262006, ["result"]),
    phrase("p030", "I do not think", "...とは思わない", "後ろにthat節を置いて判断を弱める。", "I do not think this is too hard.", "これは難しすぎるとは思いません。", 4, 15, 7744914, ["opinion"]),
    phrase("p031", "in the middle of", "...の最中に / 中央に", "時間の途中にも、場所の中央にも使う。", "He called in the middle of dinner.", "夕食の最中に彼から電話がありました。", 4, 17, 7051145, ["time", "place"]),
    phrase("p032", "in the context of", "...という文脈で", "意味や判断の背景を指定する。", "The phrase is clear in the context of the sentence.", "そのフレーズは文の文脈では明確です。", 4, 31, 6164702, ["context"]),
    phrase("p033", "it is important to", "...することが重要", "to以下を重要な行動として示す。", "It is important to review hard phrases.", "難しいフレーズを復習することが重要です。", 4, 43, 5860470, ["evaluation"]),
    phrase("p034", "to be able to", "...できるように", "目的や状態変化の中で能力を表す。", "Practice daily to be able to speak faster.", "もっと速く話せるように毎日練習しましょう。", 4, 46, 5432413, ["ability"]),
    phrase("p035", "do not have to", "...する必要はない", "禁止ではなく不要を表す。must notとは違う。", "You do not have to finish everything today.", "今日すべて終える必要はありません。", 4, 56, 4344739, ["necessity", "negative"]),
    phrase("p036", "on the one hand", "一方では", "on the other handと組み合わせて対比を作りやすい。", "On the one hand, it is simple.", "一方では、それはシンプルです。", 4, 66, 3817929, ["contrast"]),
    phrase("p037", "for a long time", "長い間", "継続している時間の長さを表す。", "I have used this phrase for a long time.", "私はこのフレーズを長い間使っています。", 4, 67, 3812328, ["time"]),
    phrase("p038", "in the first place", "そもそも", "理由や前提に立ち戻る時に使う。", "Why did we choose this in the first place?", "そもそもなぜこれを選んだのでしょうか。", 4, 74, 3605871, ["logic"]),
    phrase("p039", "with respect to the", "...に関して", "aboutより硬く、文書でよく使う。", "With respect to the data, the source is noted.", "データに関しては、出典を明記しています。", 4, 71, 3636033, ["scope"]),
    phrase("p040", "if you want to", "...したいなら", "相手の希望を条件にして提案する。", "If you want to improve, review often.", "上達したいなら、頻繁に復習しましょう。", 4, 89, 3202746, ["condition"]),
    phrase("p041", "in a way that", "...するような形で", "方法と結果をつなげる。", "Design it in a way that feels natural.", "自然に感じられる形で設計してください。", 4, 90, 3195969, ["manner"]),
    phrase("p042", "when it comes to", "...のこととなると", "話題を限定して意見を言う導入。", "When it comes to phrases, context matters.", "フレーズのこととなると、文脈が重要です。", 4, 94, 3169411, ["topic"]),
    phrase("p043", "a great deal of", "大量の / 多くの", "不可算名詞とよく使う、やや硬めの表現。", "A great deal of practice happens quietly.", "多くの練習は静かに積み重なります。", 4, 97, 3130256, ["quantity"]),
    phrase("p044", "in the same way", "同じように", "前に出た方法や考え方と対応させる。", "Use examples in the same way.", "同じように例文を使ってください。", 4, 101, 3078280, ["comparison"]),
    phrase("p045", "a wide range of", "幅広い", "種類や範囲の広さを表す。", "The corpus includes a wide range of books.", "そのコーパスには幅広い本が含まれます。", 4, 107, 3021165, ["quantity"]),
    phrase("p046", "for the sake of", "...のために", "利益や目的のために、という少し硬い表現。", "Keep it simple for the sake of speed.", "速さのためにシンプルに保ちましょう。", 4, 110, 2977392, ["purpose"]),
    phrase("p047", "in relation to the", "...との関連で", "関係性を説明する時に使う。", "The score is shown in relation to the deck.", "スコアはデッキとの関連で表示されます。", 4, 119, 2758077, ["relation"]),
    phrase("p048", "I do not want to", "...したくない", "自分の意志や拒否を言う基本形。", "I do not want to forget this phrase.", "このフレーズを忘れたくありません。", 5, 17, 4566830, ["desire", "negative"]),
    phrase("p049", "you do not have to", "...しなくていい", "相手の負担を減らす時に使いやすい。", "You do not have to study every card today.", "今日すべてのカードを学習しなくていいです。", 5, 24, 2356981, ["necessity", "negative"]),
    phrase("p050", "I do not know what", "何を...かわからない", "what以下に迷っている対象が続く。", "I do not know what to say.", "何と言えばいいかわかりません。", 5, 19, 3154645, ["thinking"]),
    phrase("p051", "by the end of the", "...の終わりまでに", "期限を表す。byはその時点までの完了を示す。", "Finish the review by the end of the day.", "その日の終わりまでに復習を終えてください。", 5, 32, 1847309, ["time"]),
    phrase("p052", "in such a way that", "...となるような方法で", "方法が結果を生むことを示す硬めの表現。", "Group phrases in such a way that meaning is clear.", "意味が明確になるような方法でフレーズを分けます。", 5, 49, 1418018, ["manner", "result"]),
    phrase("p053", "I'm not going to", "...するつもりはない", "予定や意志の否定。書き言葉の元データではI 'mの形。", "I'm not going to skip review.", "復習を飛ばすつもりはありません。", 5, 52, 1341133, ["future", "negative"], "I 'm not going to"),
    phrase("p054", "I do not know if", "...かどうかわからない", "if以下が本当か不確かな時に使う。", "I do not know if this is enough.", "これで十分かどうかわかりません。", 5, 55, 1315936, ["thinking"]),
    phrase("p055", "it should be noted that", "...に注意すべき", "論文や説明文で重要点を前置きする硬い表現。", "It should be noted that progress stays on this device.", "進捗はこの端末に残る点に注意すべきです。", 5, 56, 1302777, ["academic"]),
    phrase("p056", "one of the most important", "最も重要な...の一つ", "最上級を少し柔らかく言う形。", "Context is one of the most important clues.", "文脈は最も重要な手がかりの一つです。", 5, 57, 1291865, ["evaluation"]),
    phrase("p057", "would not be able to", "...できないだろう", "仮定や丁寧な推量の中で能力の否定を表す。", "Without examples, I would not be able to remember it.", "例文なしでは、それを覚えられないでしょう。", 5, 63, 1215687, ["ability", "negative"]),
    phrase("p058", "there are a number of", "いくつかの...がある", "複数の存在をやや硬めに示す。", "There are a number of phrases to review.", "復習すべきフレーズがいくつかあります。", 5, 75, 1113994, ["quantity", "existence"]),
    phrase("p059", "as a matter of fact", "実際のところ", "相手の理解を補正したり、事実を強調したりする。", "As a matter of fact, short sessions work well.", "実際のところ、短い学習時間はよく効きます。", 5, 77, 1087196, ["emphasis"]),
    phrase("p060", "do not want to be", "...になりたくない", "状態や役割になることへの拒否を表す。", "I do not want to be confused by one word.", "一つの単語で混乱したくありません。", 5, 90, 1033730, ["desire", "negative"]),
    phrase("p061", "I do not know why", "なぜ...かわからない", "理由が不明な時の定番。", "I do not know why this phrase feels hard.", "なぜこのフレーズが難しく感じるのかわかりません。", 5, 91, 1031089, ["thinking"]),
    phrase("p062", "you do not need to", "...する必要はない", "do not have toと近く、不要をやわらかく言える。", "You do not need to memorize every word alone.", "すべての単語を単独で覚える必要はありません。", 5, 105, 949497, ["necessity", "negative"]),
    phrase("p063", "I do not think so", "そうは思わない", "意見へのやわらかい否定。", "I do not think so, but let's test it.", "そうは思いませんが、試してみましょう。", 5, 115, 917052, ["opinion", "negative"]),
    phrase("p064", "such as", "...のような", "例を挙げる時の基本表現。", "Use phrases such as as soon as and in terms of.", "as soon asやin terms ofのようなフレーズを使います。", 2, 51, 98653699, ["example"]),
    phrase("p065", "have been", "ずっと...である / ...されてきた", "現在完了の継続や受け身でよく出る。", "These phrases have been common for years.", "これらのフレーズは何年もよく使われてきました。", 2, 38, 111420949, ["grammar"]),
    phrase("p066", "can be", "...になり得る / ...できる", "可能性と受け身の両方で頻出する。", "A short phrase can be easier to remember.", "短いフレーズは覚えやすいことがあります。", 2, 26, 137795460, ["ability", "possibility"]),
    phrase("p067", "would be", "...だろう / ...でしょう", "仮定、推量、丁寧な言い方で使う。", "That would be a good place to start.", "そこから始めるのがよいでしょう。", 2, 53, 93616008, ["modal"]),
    phrase("p068", "may be", "...かもしれない", "可能性を控えめに示す。", "This may be useful for review.", "これは復習に役立つかもしれません。", 2, 55, 90202200, ["possibility"]),
    phrase("p069", "does not", "...しない / ...ではない", "三人称単数の否定。後ろの動詞や形容詞で意味が決まる。", "The app does not need an account.", "このアプリはアカウントを必要としません。", 2, 58, 86982086, ["negative"]),
    phrase("p070", "will be", "...になるだろう / ...されるだろう", "未来の状態や受け身でよく出る。", "Your progress will be saved here.", "進捗はここに保存されます。", 2, 59, 85649314, ["future"]),
    phrase("p071", "out of", "...の外へ / ...から / ...中", "移動、材料、範囲など意味が広いので後ろの語で判断する。", "Pick five cards out of the deck.", "デッキの中から5枚選びます。", 2, 42, 107336419, ["movement", "scope"]),
    phrase("p072", "there is", "...がある / いる", "新しい情報を出す入口になる。", "There is one card left.", "カードが1枚残っています。", 2, 50, 99213056, ["existence"]),
    phrase("p073", "and then", "それから / その後", "出来事の順番をつなげる。", "Tap the card, and then swipe.", "カードをタップし、それからスワイプします。", 2, 78, 73537682, ["sequence"]),
    phrase("p074", "if you", "もしあなたが...なら", "条件を相手に向けて始める表現。", "If you miss it, send it to review.", "間違えたら、復習に送ってください。", 2, 68, 80339245, ["condition"])
  ];
})();
